### ISSUE TITLE
TypeError in Object.getDiffString

### ISSUE THREAD

**Issue by RoadRunnr** [googleapis/code-suggester#376]
#### Environment details

  - OS: Ubuntu-22.04 (GH Actions image)
  - Node.js version: I have not idea, whatever is included in the GH Image
  - npm version: I have not idea, whatever is included in the GH Image
  - `code-suggester` version: googleapis/code-suggester@v3

#### Steps to reproduce

Crashes with:

```
TypeError: Cannot read property 'error' of undefined
    at Object.getDiffString (/home/runner/work/_actions/googleapis/code-suggester/v3/action/webpack:/build/src/bin/handle-git-dir-change.js:220:1)
    at run (/home/runner/work/_actions/googleapis/code-suggester/v3/action/dist/index.js:12917:56)
    at /home/runner/work/_actions/googleapis/code-suggester/v3/action/dist/index.js:12975:5
    at /home/runner/work/_actions/googleapis/code-suggester/v3/action/dist/index.js:12978:3
    at Object.<anonymous> (/home/runner/work/_actions/googleapis/code-suggester/v3/action/dist/index.js:12981:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
Error: Cannot read property 'error' of undefined
```

sample GH Actions run: https://github.com/travelping/ergw_internal/runs/6706402960?check_suite_focus=true

**Comment by RoadRunnr** [comment]
So, I tried to run it with the suggested versions of the image and the action from the sample in the doc (https://github.com/googleapis/code-suggester#review-a-pull-request) and it also fails with almost the same error:

```
TypeError: Cannot read property 'error' of undefined
    at Object.getDiffString (/home/runner/work/_actions/googleapis/code-suggester/v2/action/webpack:/build/src/bin/handle-git-dir-change.js:220:1)
```

The only difference is the version in there (v2 vs. v3).

**Comment by chingor13** [comment]
This looks like there is an error in `getDiffString()` and it's trying to log the error on an undefined logger.
